/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { Environment, useGLTF } from "@react-three/drei";

export function Conve(props) {
   const { nodes, materials } = useGLTF("/models/editConveyor.glb");
   return (
      <>
         {/* <Environment preset="city" /> */}
         <group {...props} dispose={null}>
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group118695764.geometry}
               material={materials["mat23.001"]}
               position={[0.39, 0.015, -0.024]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group1259534448.geometry}
               material={materials["mat23.001"]}
               position={[0.39, 0.015, -0.264]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group1742506544.geometry}
               material={materials["mat23.001"]}
               position={[0.389, 0.015, -0.264]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group560991445.geometry}
               material={materials["mat23.001"]}
               position={[0.99, 0.014, -0.024]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group276360129.geometry}
               material={materials["mat23.001"]}
               position={[0.99, 0.014, -0.024]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group553805402.geometry}
               material={materials["mat23.001"]}
               position={[0.99, 0.013, -0.265]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group1245459876.geometry}
               material={materials["mat23.001"]}
               position={[0.99, 0.013, -0.264]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group37982561.geometry}
               material={materials["mat16.002"]}
               position={[0.084, 0.026, -0.267]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group810781124.geometry}
               material={materials["mat16.002"]}
               position={[0.084, 0.026, -0.027]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group827098980.geometry}
               material={materials["mat23.001"]}
               position={[0.39, 0.015, -0.024]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group1523430255.geometry}
               material={materials["mat23.001"]}
               position={[-0.21, 0.014, -0.264]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group2015598450.geometry}
               material={materials["mat22.001"]}
               position={[-0.912, 0.056, -0.144]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group1841975321.geometry}
               material={materials["mat22.001"]}
               position={[-0.984, 0.056, -0.144]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group1400634884.geometry}
               material={materials["mat22.001"]}
               position={[-0.948, 0.056, -0.144]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group494692606.geometry}
               material={materials["mat22.001"]}
               position={[-1.056, 0.056, -0.144]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group1280261175.geometry}
               material={materials["mat23.001"]}
               position={[-0.87, 0.007, -0.264]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group949196155.geometry}
               material={materials["mat23.001"]}
               position={[-1.098, 0.007, -0.264]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group510726090.geometry}
               material={materials["mat23.001"]}
               position={[-0.822, 0.014, -0.264]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group815604096.geometry}
               material={materials["mat23.001"]}
               position={[-1.098, 0.007, -0.024]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group1836902502.geometry}
               material={materials["mat23.001"]}
               position={[-0.822, 0.014, -0.024]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group1740984658.geometry}
               material={materials["mat23.001"]}
               position={[-1.098, 0.007, -0.024]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group662161758.geometry}
               material={materials["mat23.001"]}
               position={[-0.822, 0.014, -0.024]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group417174269.geometry}
               material={materials["mat23.001"]}
               position={[-0.87, 0.007, -0.024]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group1533488536.geometry}
               material={materials["mat23.001"]}
               position={[-0.21, 0.014, -0.264]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group1145278412.geometry}
               material={materials["mat16.002"]}
               position={[-1.099, 0.026, -0.144]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group518932168.geometry}
               material={materials["mat16.002"]}
               position={[-0.871, 0.026, -0.143]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group1496666282.geometry}
               material={materials["mat23.001"]}
               position={[-0.87, 0.007, -0.024]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group161396369.geometry}
               material={materials["mat15.003"]}
               position={[0.084, 0.056, -0.144]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group1963601617.geometry}
               material={materials["mat16.002"]}
               position={[0.389, 0.026, -0.143]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group581646163.geometry}
               material={materials["mat16.002"]}
               position={[-0.211, 0.026, -0.144]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group413408637.geometry}
               material={materials["mat16.002"]}
               position={[-0.823, 0.026, -0.144]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group323396810.geometry}
               material={materials["mat16.002"]}
               position={[0.989, 0.026, -0.144]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group512570650.geometry}
               material={materials["mat23.001"]}
               position={[0.084, 0.074, -0.144]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group884165777.geometry}
               material={materials["mat23.001"]}
               position={[0.996, 0.056, -0.144]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group160355870.geometry}
               material={materials["mat23.001"]}
               position={[0.084, 0.038, -0.144]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group1508755916.geometry}
               material={materials["mat23.001"]}
               position={[-0.828, 0.056, -0.144]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group1807440170.geometry}
               material={materials["mat22.001"]}
               position={[-0.876, 0.056, -0.144]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group1417346186.geometry}
               material={materials["mat23.001"]}
               position={[-0.21, 0.014, -0.024]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group271065018.geometry}
               material={materials["mat22.001"]}
               position={[-1.092, 0.056, -0.144]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group848837919.geometry}
               material={materials["mat15.003"]}
               position={[-0.984, 0.038, -0.144]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group1738671895.geometry}
               material={materials["mat22.001"]}
               position={[-1.02, 0.056, -0.144]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group959160456.geometry}
               material={materials["mat23.001"]}
               position={[-0.822, 0.014, -0.264]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group653319785.geometry}
               material={materials["mat23.001"]}
               position={[-0.87, 0.007, -0.264]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group177006488.geometry}
               material={materials["mat23.001"]}
               position={[-0.21, 0.014, -0.024]}
               scale={1.2}
            />
            <mesh
               castShadow
               receiveShadow
               geometry={nodes.group1005767962.geometry}
               material={materials["mat23.001"]}
               position={[-1.098, 0.007, -0.264]}
               scale={1.2}
            />
         </group>
      </>
   );
}

useGLTF.preload("/models/editConveyor.glb");
