/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";

export function Jud(props) {
   const { nodes, materials } = useGLTF("/models/yesca logo 22.glb");

   // 📝 Add Leva controls for each mesh wireframe toggle
   const { wireframe1, wireframe2, wireframe3, wireframe4 } = useControls({
      wireframe1: { value: false, label: "3DGeom-3 Wireframe" },
      wireframe2: { value: false, label: "3DGeom-4 Wireframe" },
      wireframe3: { value: false, label: "3DGeom-1 Wireframe" },
      wireframe4: { value: false, label: "3DGeom-2 Wireframe" },
   });

   // ✅ Clone materials to avoid mutating GLTF cache globally
   const mat3 = nodes["3DGeom-3"].material.clone();
   mat3.wireframe = wireframe1;

   const mat4 = materials["*2"].clone();
   mat4.wireframe = wireframe2;

   const mat1 = materials["*1"].clone();
   mat1.wireframe = wireframe3;

   const mat2 = nodes["3DGeom-2"].material.clone();
   mat2.wireframe = wireframe4;

   return (
      <group {...props} dispose={null}>
         <group rotation={[-Math.PI / 2, 0, 0]}>
            <group scale={0.025}>
               <group position={[10.339, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                     castShadow
                     receiveShadow
                     geometry={nodes["3DGeom-3"].geometry}
                     material={mat3}
                  />
                  <mesh
                     castShadow
                     receiveShadow
                     geometry={nodes["3DGeom-4"].geometry}
                     material={mat4}
                  />
               </group>
               <mesh
                  visible={false}
                  castShadow
                  receiveShadow
                  geometry={nodes["3DGeom-1"].geometry}
                  material={mat1}
                  position={[23.426, -0.2, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes["3DGeom-2"].geometry}
                  material={mat2}
                  position={[-0.006, -4, 10.851]}
                  rotation={[Math.PI / 2, 0, 0]}
               />
            </group>
         </group>
      </group>
   );
}

useGLTF.preload("/models/yesca logo 22.glb");
